# Generated by nixos-generate-config on HP ProDesk 400 G3 SFF
# CPU: Intel i5-6500 (4c/4t @ 3.2GHz) | RAM: 4GB DDR4
# NIC: Realtek RTL8111 (enp1s0) | GPU: Intel HD 530
# Storage: SanDisk SSD PLUS 480GB (internal SATA)
{ config, lib, ... }:

{
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "uas"
    "sd_mod"
    "sr_mod"
    "tpm_tis"
    "tpm_crb"
  ];
}
